vservices:

  postgresql:
    image: postgres:16
    container_name: safelink-database
    restart: always
    environment:
      POSTGRES_DB: safelink
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  safelink:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: safelink-api
    depends_on:
      - postgresql
    restart: always
    environment:
      DATABASE_URL: jdbc:postgresql://postgresql:5432/safelink
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      PRIVATE_KEY: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC0AvDei4OWJznIR+VYc1I7CH7DDvZMumZqeaQ1fQpk+yCS1thznBAjC+a0wyphInc019eyZ7pxWgM9RDl+DTl7nt6ztpHZ7eRfueusyxqEJjdQYY5HXd/yOnc/3zOI4ypJzMq3FL1/OJ5X5wSXrX8370HTjak4eOHAsFbY7D3n9oXIq9yH5SZBjPJKMRrKtsD5WK1ooSrVL0pBclSZiwfWKxYzSsSqncN4rJhKKpZ993R+Mxm0JGVDmt1HrUAWgZ+9eMrsoIi7zgWhQHO2QxFFdSwM0OWh4qGBJrE5XkOVODTYFqoOrxT44P2wGg+mKrFGlGdIjPs/HG7M0N8Ae92hAgMBAAECggEAXqx9Sk5N8pbGyRMnCBH+2ZVqNeSUnV4bpzw6pPcSlHGPfCsKxCL8SbJksAVFMLkTwPMUOnxbjmos8fgD1MvXw7CWqCYJJ3j6d24tCT/4vi/rP5dPYTF6KsedGDanwALZpt7Sbt+1mkeI3+pce/l/w0dOc5k5ur243cLgqk31cR1QX4hNc8Dqb2kxhllYqVqEta5MtD6Js00riHbTN9FfIUdvf7Squrkz4/siwebwGFRY2HNVBPSlT1ublLS7gl47E1mKUoYWj5TKUJOc9hxnZlnLl8zfx59FOWG8g0Ax5W2Q76CEtepe2C5JCoi4LZvhKo6wvuxHHpAX02UVcdzM0QKBgQDnv36LXVhL6mUgOVWgp7FfZiQ/NaZ4OQY/tPUVMLkx145m6yKtTDQ5esotlZguxKwZ3R0WeRVYcKk2Jyu2+VHo3xK8ED4YduJ3Q+PopSql3EUNV8Nb5lq0HEKxazwFZeb4Jm9dV7kmXGj5A1FlIcxJ7LS1CCxeWg3/8SwR0xoTqwKBgQDG2W4avUsuLQ+hdz3warbYf13i2Kug3Dh/lsfZQFKDHgZaUkGfaNcsqvmChid/ldk77yi/doX1DpedFUYWPLHEs4Y/+ApQf4pOLwgCsONwDgDHj0olnEjR2Wp5/WUjb1f2occ76UOslFmWY92XMGlYeoZWcIcSC3nAvS+BVrhH4wKBgQCMVruEG8/nkRcSL4Y6FrLj6Y/Ts2KO9UFifOvZnDraAwYaLxQ9y6LomAItHqUc1T6/HtaJkGOrvfXKdGgVkt/WXJgUyOVBnWTBApzWeobcEArE7LvCQDn3ThHZLO4Y+r+m0GeqKABYSafL/AVjb9ctgSlhY4Sy0mgd8OdWF/d3pwKBgQCNb+RgAppx+r0udRlKYy0xKs8F5mWVYm6RWhdGUPkfqACOyAlDMJg0flxA2dlIZ7Z/aeoK3WwE1V9D7PjQIlWzepoX7/6uKTmfyNYiy9zKPDuTtjjgLZyiHsocgP8qSC1CEOoclBt9qntafCgGPPoBZA0feKSqUh1E2YvrrFohTwKBgQDftIOfo9Retb5K+vm1WeJxfjCudpvIjdyzK3LndRCBrvXSpFwHBhLOPggTLCFV2tMMccYjmJkq+VYPpg1EtmIYxOYmX2LSfmYmHo2bd3HxmFAENl6gQIV7vPM+pHfBZfZ3CAQ3F1Xjh7Wgidkvu8k73ojFWIFS9TjxLcM3QYNpxA==
      PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtALw3ouDlic5yEflWHNSOwh+ww72TLpmanmkNX0KZPsgktbYc5wQIwvmtMMqYSJ3NNfXsme6cVoDPUQ5fg05e57es7aR2e3kX7nrrMsahCY3UGGOR13f8jp3P98ziOMqSczKtxS9fzieV+cEl61/N+9B042pOHjhwLBW2Ow95/aFyKvch+UmQYzySjEayrbA+VitaKEq1S9KQXJUmYsH1isWM0rEqp3DeKyYSiqWffd0fjMZtCRlQ5rdR61AFoGfvXjK7KCIu84FoUBztkMRRXUsDNDloeKhgSaxOV5DlTg02BaqDq8U+OD9sBoPpiqxRpRnSIz7PxxuzNDfAHvdoQIDAQAB
    ports:
      - "8080:8080"

volumes:
  postgres_data: